version: '3.8'
services:
  reverse-proxy:
    image: library/traefik:v2.2
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web-secure.address=:443"
      - "--providers.file.directory=/configuration/"
      - "--providers.file.watch=true"
    networks:
      - reverse-proxy
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "8443:8443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./reverse-proxy/:/configuration/
      - ./reverse-proxy/certs/:/certs/
networks:
  reverse-proxy: