version: '3.8'
services:
  test-app:
    build: ./test-app
    depends_on:
      - reverse-proxy
    networks:
      - reverse-proxy
      - idp
    labels:
      - "traefik.http.routers.testapp.rule=Host(`test-app.unicon.local`)"
      - "traefik.http.services.testapp.loadbalancer.server.port=8080"
      - "traefik.http.routers.testapp.tls=true"
      - "traefik.docker.network=learning-env_reverse-proxy"
      - "traefik.enable=true"
networks:
  grouper:
  reverse-proxy: