version: '3.8'
services:
  mongo:
    image: mongo:4
    volumes:
    - mongo_data:/data/db:rw
    tmpfs:
      - /tmp
    networks:
      - graylog
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.5
    volumes:
    - elasticsearch_data:/usr/share/elasticsearch/data:rw
    tmpfs:
      - /tmp
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Xlog:disable -Xlog:all=warning:stderr:utctime,level,tags -Xlog:gc=debug:stderr:utctime"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - graylog
  graylog:
    image: graylog/graylog:3.3
    labels:
      - "traefik.http.routers.logs.rule=Host(`logs.unicon.local`)"
      - "traefik.http.services.logs.loadbalancer.server.port=9000"
      - "traefik.http.routers.logs.tls=true"
      - "traefik.docker.network=learning-env_reverse-proxy"
      - "traefik.enable=true"
    volumes:
    - graylog_data:/usr/share/graylog/data/journal:rw
    tmpfs:
      - /tmp
    environment:
      - GRAYLOG_PASSWORD_SECRET=asdpufoiausdpfoauispdfouoasduif
      # Password: letmein7
      - GRAYLOG_ROOT_PASSWORD_SHA2=b099dd7b1840b66cd323fb632e447e51559a14206c4aaba306f74031cf47a40a
      - GRAYLOG_HTTP_EXTERNAL_URI=https://logs.unicon.local/
      # - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
    networks:
      - graylog
      - reverse-proxy
    depends_on:
      - mongo
      - elasticsearch
    ports:
    - 1514:1514
    - 1514:1514/udp
    - 12201:12201
    - 12201:12201/udp
  reverse-proxy:
    image: library/traefik:v2.2
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web-secure.address=:443"
      - "--providers.file.directory=/configuration/"
      - "--providers.file.watch=true"
    networks:
      reverse-proxy:
        aliases:
          - idp.unicon.local
          - cas.unicon.local
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "8443:8443"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./reverse-proxy/:/configuration/
    - ./reverse-proxy/certs/:/certs/
  directory:
    build: ./directory
#    logging:
#      driver: gelf
#      options:
#        gelf-address: udp://localhost:12201
    networks:
      - idp
      - grouper
#    ports:
#    - 389:389
#    - 636:636
    volumes:
    - directory_data:/var/lib/ldap
    - directory_config:/etc/ldap/slapd.d
    - ./directory/certs:/container/service/slapd/assets/certs
    environment:
      LDAP_BASE_DN: "dc=unicon,dc=local"
      LDAP_DOMAIN: "unicon.local"
      HOSTNAME: "directory"
      LDAP_TLS_VERIFY_CLIENT: "try"
  shibboleth-idp:
    build: ./shibboleth-idp
    labels:
      - "traefik.http.routers.idp.rule=Host(`idp.unicon.local`)"
      - "traefik.http.services.idp.loadbalancer.server.port=8080"
      - "traefik.http.routers.idp.tls=true"
      - "traefik.docker.network=learning-env_reverse-proxy"
      - "traefik.enable=true"
#    logging:
#      driver: gelf
#      options:
#        gelf-address: udp://localhost:12201
    depends_on:
      # - graylog
      - directory
      - reverse-proxy
    networks:
      - graylog
      - idp
      - reverse-proxy
    volumes:
    - ./directory/certs/ca.crt:/opt/shibboleth-idp/credentials/ldap-server.crt
    - ./shibboleth-idp/metadata/dynamic:/opt/shibboleth-idp/metadata/dynamic
    healthcheck:
      disable: true
  database:
    image: postgres:12.3
    command: postgres -N 500
#    logging:
#      driver: gelf
#      options:
#        gelf-address: udp://localhost:12201
    networks:
      - grouper
    ports:
    - "5432:5432"
    volumes:
    - ./database/initdb.d/:/docker-entrypoint-initdb.d/
    - ./database/data/:/tmp/pdata/
    - database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=supersecret
  grouper-ui:
    build: ./grouper
    command: ui
    labels:
      - "traefik.http.routers.grouperui.rule=Host(`grouper-ui.unicon.local`)"
      - "traefik.http.services.grouperui.loadbalancer.server.port=8080"
      - "traefik.http.routers.grouperui.tls=true"
      - "traefik.docker.network=learning-env_reverse-proxy"
      - "traefik.enable=true"
#    logging:
#      driver: gelf
#      options:
#        gelf-address: udp://localhost:12201
    depends_on:
      - database
      - directory
    networks:
      - graylog
      - grouper
      - reverse-proxy
    volumes:
      - ./grouper/src/main/docker/slashRoot/opt/grouper/grouperWebapp/WEB-INF/classes/log4j.properties.sample:/opt/grouper/grouperWebapp/WEB-INF/classes/log4j.properties
      - ./grouper/src/main/docker/slashRoot/opt/grouper/grouperWebapp/WEB-INF/classes/grouper.hibernate.properties.sample:/opt/grouper/grouperWebapp/WEB-INF/classes/grouper.hibernate.properties
    environment:
      GROUPER_DATABASE_URL: "jdbc:postgresql://database/grouper"
      GROUPER_DATABASE_USERNAME: "grouper"
      GROUPER_DATABASE_PASSWORD: "grouper"
      GROUPER_MORPHSTRING_ENCRYPT_KEY: "THISISSUPERSECRET!"
      GROUPER_AUTO_DDL_UPTOVERSION: "v2.5.*"
      GROUPER_RUN_TOMCAT_NOT_SUPERVISOR: "true"
      GROUPER_UI_CONFIGURATION_EDITOR_SOURCEIPADDRESSES: "0.0.0.0/0"
      GROUPER_UI_GROUPER_AUTH: "true"
      GROUPERSYSTEM_QUICKSTART_PASS: "letmein7"
      RUN_SHIB_SP: "false"
  grouper-daemon:
    build: ./grouper
    command: daemon
    depends_on:
      - database
      - directory
    networks:
      - graylog
      - grouper
    environment:
      GROUPER_DATABASE_URL: "jdbc:postgresql://database/grouper"
      GROUPER_DATABASE_USERNAME: "grouper"
      GROUPER_DATABASE_PASSWORD: "grouper"
      GROUPER_MORPHSTRING_ENCRYPT_KEY: "THISISSUPERSECRET!"
      GROUPER_AUTO_DDL_UPTOVERSION: "v2.5.*"
  midpoint:
    build: ./midpoint
    labels:
      - "traefik.http.routers.midpoint.rule=Host(`midpoint.unicon.local`)"
      - "traefik.http.services.midpoint.loadbalancer.server.port=8080"
      - "traefik.http.routers.midpoint.tls=true"
      - "traefik.docker.network=learning-env_reverse-proxy"
      - "traefik.enable=true"
    depends_on:
      - database
    networks:
      - reverse-proxy
      - grouper
    environment:
      AUTHENTICATION: "internal"
      REPO_DATABASE_TYPE: "postgresql"
      REPO_JDBC_URL: "default"
      REPO_HOST: "database"
      REPO_PORT: "default"
      REPO_DATABASE: "midpoint"
      REPO_USER: "midpoint"
      REPO_MISSING_SCHEMA_ACTION: "create"
      REPO_UPGRADEABLE_SCHEMA_ACTION: "stop"
      MP_MEM_MAX: "2048m"
      MP_MEM_INIT: "1024m"
      TIMEZONE: "UTC"
      AJP_ENABLED: "false"
    secrets:
        - mp_database_password.txt
        - mp_keystore_password.txt
        - mp_host-key.pem
        - mp_shibboleth_sp_keys.jks
    volumes:
      - midpoint_home:/opt/midpoint/var
      - type: bind
        source: ./midpoint/secrets/shibboleth/idp-metadata.xml
        target: /etc/shibboleth/idp-metadata.xml
      - type: bind
        source: ./midpoint/secrets/httpd/host-cert.pem
        target: /etc/pki/tls/certs/host-cert.pem
      - type: bind
        source: ./midpoint/secrets/httpd/host-cert.pem
        target: /etc/pki/tls/certs/cachain.pem
    healthcheck:
      disable: true
  test-app:
    build: ./test-app
    depends_on:
      - reverse-proxy
    labels:
      - "traefik.http.routers.testapp.rule=Host(`test-app.unicon.local`)"
      - "traefik.http.services.testapp.loadbalancer.server.port=8080"
      - "traefik.http.routers.testapp.tls=true"
      - "traefik.docker.network=learning-env_reverse-proxy"
      - "traefik.enable=true"
    networks:
      - reverse-proxy
      - idp
    volumes:
    - ./test-app/etc/test-app:/etc/test-app
    - ./cacerts:/usr/lib/jvm/zulu11-ca/lib/security/cacerts
  cas:
    build: ./cas
    depends_on:
      - reverse-proxy
    networks:
      - reverse-proxy
      - idp
    labels:
      - "traefik.http.routers.cas.rule=Host(`cas.unicon.local`)"
      - "traefik.http.services.cas.loadbalancer.server.port=8080"
      - "traefik.http.routers.cas.tls=true"
      - "traefik.docker.network=learning-env_reverse-proxy"
      - "traefik.enable=true"
  cas-management:
    build: ./cas-management
    depends_on:
      - reverse-proxy
      - cas
    networks:
      - reverse-proxy
      - idp
    labels:
      - "traefik.http.routers.cas-management.rule=Host(`cas-management.unicon.local`)"
      - "traefik.http.services.cas-management.loadbalancer.server.port=8080"
      - "traefik.http.routers.cas-management.tls=true"
      - "traefik.docker.network=learning-env_reverse-proxy"
      - "traefik.enable=true"
    volumes:
      - ./cacerts:/opt/java/openjdk/lib/security/cacerts

networks:
  graylog:
  idp:
  grouper:
  reverse-proxy:
volumes:
  elasticsearch_data:
    driver: local
  mongo_data:
    driver: local
  graylog_data:
    driver: local
  database_data:
    driver: local
  directory_data:
    driver: local
  directory_config:
    driver: local
  midpoint_home:
    driver: local
secrets:
  # midPoint
  mp_host-key.pem:
    file: ./midpoint/secrets/httpd/host-key.pem
  mp_database_password.txt:
    file: ./midpoint/secrets/application/database_password.txt
  mp_keystore_password.txt:
    file: ./midpoint/secrets/application/keystore_password.txt
  mp_shibboleth_sp_keys.jks:
    file: ./midpoint/secrets/shibboleth/shibboleth_sp_keys.jks
